from riplib.ass import AssClient
import time

# Initialize the AssClient
ass = AssClient()

# Define a listener using the on_rip decorator
@ass.on_rip
def on_rip(fart):
    """
    Handles rip events by printing the fart's attributes.

    Args:
        fart: The fart instance generated by the AssClient.
    """
    print(f"[[ SELF.RIPPED ]] {fart.smell}, {fart.power}, {fart.persistence}, {fart.soup}")

# Generate and handle farts in a loop
for _ in range(10):
    fart = ass.rip()
    if fart.is_burst():
        print("[[ BURST. DETECTED. ]]")
    time.sleep(2)
